it('asks for a character guess', () => {
  cy.visit('/')
      .get('div.centered')
      .get('div.guess')
      .get('div')
      .contains("What's your next guess?")
      .should('be.visible')
      .next('div')
      .get('input[type="text"]')
      .next('button[type="button"]#confirmGuess')
      .contains('Confirm')
})
